version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      frontend:
        condition: service_healthy
      bias-detection-service:
        condition: service_healthy
    restart: always

  bias-detection-service:
    build:
      context: ./src/lib/ai/bias-detection
      dockerfile: Dockerfile
    # No direct port mapping to host, Nginx will proxy
    environment:
      BIAS_SERVICE_HOST: 0.0.0.0
      BIAS_SERVICE_PORT: 5001
      GUNICORN_WORKERS: 4
      GUNICORN_WORKER_CLASS: gevent
      GUNICORN_TIMEOUT: 120
      GUNICORN_LOGLEVEL: info
      GUNICORN_DAEMON: "false"
      GUNICORN_PRELOAD_APP: "false"
    restart: always
    volumes:
      - ./src/lib/ai/bias-detection:/app
    healthcheck:
      test: ["CMD", "/app/check_service_health.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    # No direct port mapping to host, Nginx will proxy
    environment:
      NODE_ENV: production
      # Frontend will access backend via Nginx or directly via service name
      NEXT_PUBLIC_BIAS_API_URL: http://nginx/api/bias-detection # Example for frontend to use Nginx
    depends_on:
      bias-detection-service:
        condition: service_healthy
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s